---
- name: Load SSH Pub Key if it exists
  ansible.builtin.slurp:
    src: "{{ beszel_hub_install_dir }}/beszel_data/id_ed25519.pub"
  register: b64_pub_key
  when: 'not beszel_public_key'

- name: Register local_public_key
  ansible.builtin.set_fact:
    local_public_key: "{{ b64_pub_key.content | ansible.builtin.b64decode | trim }}"
  when: 'not beszel_public_key'

- name: Assert beszel_public_key is set
  ansible.builtin.assert:
    that: 'not (beszel_public_key == "" and local_public_key == "")'
    fail_msg: Provide a public key to be used by the Beszel binary agent.

- name: Determine Beszel binary agent architecture
  ansible.builtin.set_fact:
    beszel_architecture: >-
      {% if ansible_architecture == 'x86_64' %}
        amd64
      {% elif ansible_architecture == 'aarch64' %}
        arm64
      {% elif ansible_architecture == 'armv6l' %}
        arm
      {% elif ansible_architecture == 'armv7l' %}
        arm
      {% endif %}

- name: Download Beszel binary agent tarball
  ansible.builtin.get_url:
    url: |
      {% if beszel_version == 'latest' %}
        https://github.com/henrygd/beszel/releases/{{ beszel_version }}/download/beszel-agent_linux_{{ beszel_architecture | trim }}.tar.gz
      {% else %}
        https://github.com/henrygd/beszel/releases/download/{{ beszel_version }}/beszel-agent_linux_{{ beszel_architecture | trim }}.tar.gz
      {% endif %}
    dest: /tmp/beszel-agent.tar.gz
    force: true
    mode: u=rw,g=,o=

- name: Extract Beszel binary agent tarball
  ansible.builtin.unarchive:
    src: /tmp/beszel-agent.tar.gz
    dest: "{{ beszel_agent_install_dir }}"
    mode: u=rwx,g=rx,o=rx
    remote_src: true
  notify: Restart Beszel binary agent systemd service

- name: Install Beszel binary agent systemd service
  ansible.builtin.template:
    src: beszel-agent.service.j2
    dest: /etc/systemd/system/beszel-agent.service
    mode: u=rw,g=r,o=r
  notify:
    - Reload systemd configuration
    - Restart Beszel binary agent systemd service

- name: Start the Beszel binary agent systemd service
  ansible.builtin.service:
    name: beszel-agent
    enabled: "{{ beszel_agent_service_enabled }}"
    state: "{{ beszel_agent_service_state }}"
