---
# present tasks file for dbrennand.beszel
- name: beszel_present | Assert beszel_public_key is set
  ansible.builtin.assert:
    that: beszel_public_key != ""
    fail_msg: Provide a public key to be used by the Beszel binary agent.

- name: beszel_present | Determine Beszel binary agent architecture
  ansible.builtin.set_fact:
    beszel_architecture: >-
      {% if ansible_architecture == 'x86_64' %}
        amd64
      {% elif ansible_architecture == 'aarch64' %}
        arm64
      {% elif ansible_architecture == 'armv6l' %}
        arm
      {% elif ansible_architecture == 'armv7l' %}
        arm
      {% endif %}

- name: beszel_present | Download Beszel binary agent tarball
  ansible.builtin.get_url:
    url: "https://github.com/henrygd/beszel/releases/{{ beszel_version }}/download/beszel-agent_linux_{{ beszel_architecture | trim }}.tar.gz" # noqa yaml[line-length]
    dest: /tmp/beszel-agent.tar.gz
    mode: u=rw,g=,o=

- name: beszel_present | Extract Beszel binary agent tarball
  ansible.builtin.unarchive:
    src: /tmp/beszel-agent.tar.gz
    dest: "{{ beszel_install_dir }}"
    mode: u=rwx,g=rx,o=rx
    remote_src: true

- name: beszel_present | Install Beszel binary agent systemd service
  notify: Reload systemd configuration
  ansible.builtin.template:
    src: beszel-agent.service.j2
    dest: /etc/systemd/system/beszel-agent.service
    mode: u=rw,g=r,o=r

- name: beszel_present | Start the Beszel binary agent systemd service
  ansible.builtin.service:
    name: beszel-agent
    enabled: "{{ beszel_service_enabled }}"
    state: "{{ beszel_service_state }}"
