---
services:
  beszel:
    image: docker.io/henrygd/beszel:0.9.1
    container_name: beszel
    restart: unless-stopped
    networks:
      - beszel
    ports:
      - 8090:8090
    volumes:
      - beszel_data:/beszel_data

volumes:
  beszel_data:

networks:
  beszel:
