---
- name: Create
  hosts: localhost
  gather_facts: false
  vars:
    molecule_inventory:
      all:
        hosts: {}
        children:
          molecule: {}
  tasks:
    - name: Start Beszel Hub Docker Compose Stack
      community.docker.docker_compose_v2:
        project_src: ../
        state: present

    - name: Create Beszel Hub Superuser
      community.docker.docker_compose_v2_exec:
        project_src: ../
        service: beszel
        command: /beszel superuser upsert molecule@example.com molecule

    - name: Get Beszel Hub PocketBase API token
      register: resp
      ansible.builtin.uri:
        # https://github.com/vaphes/pocketbase/blob/master/pocketbase/services/admin_service.py#L75
        url: http://localhost:8090/api/collections/_superusers/auth-with-password
        method: POST
        headers:
          Authorization: ""
        body:
          identity: molecule@example.com
          password: molecule
        body_format: json

    - name: Get Beszel Public Key
      register: test
      ansible.builtin.uri:
        url: http://localhost:8090/api/beszel/getkey
        method: GET
        headers:
          Authorization: "{{ resp.json.token }}"

    - name: Create container
      community.docker.docker_container:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        command: "{{ item.command }}"
        tmpfs: "{{ item.tmpfs }}"
        volumes: "{{ item.volumes }}"
        state: started
      register: result
      loop: "{{ molecule_yml.platforms }}"

    - name: Fail if container is not running
      when: >
        item.container.State.ExitCode != 0 or
        not item.container.State.Running
      ansible.builtin.fail:
        msg: "{{ item.container.Name }} failed to start."
      loop: "{{ result.results }}"

    - name: Add container to molecule_inventory
      vars:
        inventory_partial_yaml: |
          all:
            children:
              molecule:
                hosts:
                  "{{ item.name }}":
                    ansible_connection: community.docker.docker
      ansible.builtin.set_fact:
        molecule_inventory: >
          {{ molecule_inventory | combine(inventory_partial_yaml | from_yaml, recursive=true) }}
      loop: "{{ molecule_yml.platforms }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Dump molecule_inventory
      ansible.builtin.copy:
        content: |
          {{ molecule_inventory | to_yaml }}
        dest: "{{ molecule_ephemeral_directory }}/inventory/molecule_inventory.yml"
        mode: "0600"

    - name: Force inventory refresh
      ansible.builtin.meta: refresh_inventory

    - name: Fail if molecule group is missing
      run_once: true # noqa: run-once[task]
      ansible.builtin.assert:
        that: "'molecule' in groups"
        fail_msg: |
          molecule group was not found inside inventory groups: {{ groups }}
