---
- name: GitHub Action Tasks
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Ensure /etc/apt/keyrings/ exists
      ansible.builtin.file:
        path: /etc/apt/keyrings/
        state: directory
        mode: "0755"

    - name: Download Docker GPG Key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: "0644"

    - name: Create Docker Apt Repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        filename: docker.list
        state: present
        update_cache: true

    - name: Install Docker Compose plugin inside GitHub Action
      ansible.builtin.apt:
        name: docker-compose-plugin
        state: present
