name: Molecule
on: [pull_request]
jobs:
  build:
    name: Molecule
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
      - uses: actions/checkout@v4
        with:
          path: "${{ github.repository }}"
      - uses: gofrolist/molecule-action@v2
        with:
          molecule_args: --all
        env:
          GH_ACTION: true
